# Generated by Django 2.0.7 on 2018-08-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50, null=True)),
                ('unit_number', models.CharField(max_length=50, null=True)),
                ('account_name', models.CharField(max_length=30, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('furigana', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'infodep_kitting',
            },
        ),
    ]
