# Generated by Django 2.0.7 on 2018-07-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitting',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
