# Generated by Django 2.0.7 on 2018-07-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0002_auto_20180726_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitting',
            name='unit_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
