# Generated by Django 2.0.7 on 2018-07-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0003_auto_20180726_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitting',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
