# Generated by Django 2.0.7 on 2018-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0004_auto_20180726_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitting',
            name='job_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kitting',
            name='unit_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
