# Generated by Django 2.0.7 on 2018-07-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0005_auto_20180726_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitting',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
