# Generated by Django 2.0.7 on 2018-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0007_auto_20180727_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitting',
            name='job_date',
            field=models.CharField(max_length=30, null=True, verbose_name='job date'),
        ),
    ]
