# Generated by Django 2.0.7 on 2018-08-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infodep', '0008_auto_20180802_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitting',
            name='job_date',
        ),
    ]
